permalink: /:year/:month/:day/:title.html
paginate: 10
# markdown: redcarpet

# 作者信息
author:
  name: shan2song
  email: hessiatrix@gmail.com
  link: shan2song.github.io
  github: http://github.com/shan2song
  goodreads: https://www.goodreads.com/user/show/46001922-sian-song
  soundcloud: https://soundcloud.com/sian-hansong
  youtube: https://www.youtube.com/channel/UCAhvFH5jovo5TU1HxkDZLGg
  stackoverflow: http://stackoverflow.com/users/7372433/sian-s?tab=profile
  linkedin: https://www.linkedin.com/in/shanshan-song-03899878/

# 站点信息

title: shan2song
description: My personal blog
url: http://shan2song.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/signature_sian.png
favicon: /public/img/signature_sian.png

# google analytics 设置
# ga:
#  id: UA-86324137-1
#  url: https://mathesse.github.io

# disqus 设置
# disqus:
#  shortname: shan2song

# 主题设置，自动激活某个标签
active: BOOKS

# 首页除了最新文章外显示分类
cates:
  - SET

# 中文本地化?
locals:
  tags: TAGS
  about: ABOUT
  newest: NEWEST
  archive: ARCHIVE
